spring.application.name=gerenciamento-estoque

# configuracoes do banco de dados
spring.datasource.url=jdbc:postgresql://localhost:5432/db_estoque_senai
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# configuracoes do jpa
spring.jpa.database=POSTGRESQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# configuracoes da aplicacao
spring.thymeleaf.cache=false
server.servlet.session.timeout=8h
